#DROP DATABASE IF EXISTS MD;

#CREATE DATABASE MD;
USE MD;


DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS Preferencias;
DROP TABLE IF EXISTS Joinhas;

DROP TABLE IF EXISTS Tags;

DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Usuarios;


